language: node_js
node_js:
- '12'
install:
- npm install
- npm run build
after_install:
- ls -l
- cd ..
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  target_branch: gh-pages
  local_dir: docs
  on:
    branch: master
env:
  global:
    secure: PWP1LmhgUzTuaff19Z5Q6TF4je8N2g/CArq0pixw92lJQlAgyWutiSKaAgcjM9+EaJdbeVmnKx8Z0qFjX/4Gs3cub4+rSX81qAhEHCkG4YkbrLRmWCdr/JZ20U/kglZFkTskS2FAKk357pLT9u79+D9YFabhzqN23sdlXwJMy3ZriZUJtUNLHs63ThjqSDCLD5+MW7nuj8sbw/M8FEXS32Iv0DTX+gh+QFOu7RlIvO1A4/N/lQ+5UI/vCRnlybcdEctoIFtzRVPgZfaZukFoPi+aiDTpCcaMV/8QHAwi9C4p6a8yPHqNi4xaoH10sjbzwxoGToc5y0hW9ejmMa7E1DYBsUKfs4D8XeKWgerarLB6NhjLdCbfP385G91GuURoqbdKquwp5FQG8bq9o+Yjpg/s3YTXHD874cHq8HU6AQJLOU5pInWTVrrbMjEcKnhUK7eNHkSMN3yq8N8qCPNwzBebUNFv7BdFm9XhxBAVon5TBrHWOFnDauQHpljEOsh2LR35/rIDVYwsQeUlxXru+AYiaYiEEB1NNBn+MyBWFDYXoMfr29iJbU+HFAH4dFnYJ/VV5EHV0hs+hbWRv12EQFTCqQkuoLRjAlKxkkhZY0mzgepyCcmb2aRhA4QtXeoegKQhwCVFEMRR20WCw4m/bh7qiNOjwsFJ0zb6K2kd/og=
